version: "3"

services:

  influxdb:
    image: influxdb:1.8-alpine
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: openwisp2
      INFLUXDB_USER: openwisp
      INFLUXDB_USER_PASSWORD: openwisp
      
    influxdb2:
      image: influxdb:2.1.1-alpine
      volumes:
       - influxdb-data:/var/lib/influxdb2

      ports:
       - "8086:8086"
      environment:
        DOCKER_INFLUXDB_INIT_MODE: setup
        DOCKER_INFLUXDB_INIT_USERNAME: openwisp
        DOCKER_INFLUXDB_INIT_PASSWORD: openwispPassword
        DOCKER_INFLUXDB_INIT_ORG: openwisp
        DOCKER_INFLUXDB_INIT_BUCKET: openwisp2
        DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: openwisp

volumes:
  influxdb-data: {}
